# Problem type
problem_type                : 'segmentation'

# Model
model_type                  : 'pspnet50'      # Options: ['fcn8atonce']

# Load/store options
resume_experiment           : False
pretrained_model            : 'basic'
input_model_path            : null
load_weight_only            : True

# Save options
save_weight_only            : True
model_name                  : 'pspnet50'
output_model_path           : null
basic_models_path           : null


# Loss type
loss_type                   : 'cross_entropy_segmentation'
normalize_loss              : True

# General parameters
train_samples               : -1
valid_samples               : -1
test_samples                : -1
train_batch_size            : 4
valid_batch_size            : 4
test_batch_size             : 4
train                       : True
validation                  : True
test                        : False
predict_test                : True
predict_path_output         : null

# Image properties
size_image_test             : null
resize_image_train          : null    #!!python/tuple [512, 1024]
resize_image_valid          : null    #!!python/tuple [512, 1024]
resize_image_test           : null    #!!python/tuple [512, 1024]
crop_train                  : null    #!!python/tuple [720,720] #!!python/tuple [320, 320]
grayscale                   : False   #Use this option to convert to rgb a grayscale dataset

# Dataset properties
train_dataset_path          : null
valid_dataset_path          : null
test_dataset_path           : null
train_images_txt            : '/home/grupo06/m5-project/datasets/kitti/train_images.txt'
train_gt_txt                : '/home/grupo06/m5-project/datasets/kitti/train_labels.txt'
valid_images_txt            : '/home/grupo06/m5-project/datasets/kitti/val_images.txt'
valid_gt_txt                : '/home/grupo06/m5-project/datasets/kitti/val_labels.txt'
test_images_txt             : null
test_gt_txt                 : null

labels                      : !!python/tuple ['sky', 'building', 'column_pole', 'road', 'sidewalk', 'tree', 'sign', 'fence', 'car', 'pedestrian', 'byciclist']
map_labels                  : null

num_classes                 : 11
shuffle                     : True
void_class                  : 255

# Training
epochs                      : 300
initial_epoch               : 1
valid_samples_epoch         : -1
is_training                 : True

# Optimizer
optimizer                   : 'SGD'
momentum1                   : 0.9
momentum2                   : 0.99
learning_rate               : 1.0e-3
learning_rate_bias          : 1.0e-3
weight_decay                : 5.0e-5

# Scheduler
scheduler                   : None    # ['ReduceLROnPlateau','Step','MultiStep','Exponential', None]
decay                       : 0.1
sched_patience              : 5
step_size                   : 20
milestone                   : [10]

### Save criteria
save_condition              : 'valid_mIoU'

### Early Stopping
early_stopping              : True
stop_condition              : 'valid_mIoU'
patience                    : 10

# Image preprocess
rescale                     : 1. #0.003921569
mean                        : !!python/tuple [127.5, 127.5, 127.5]  #[104.00698793, 116.66876762, 122.67891434] #[103.939, 116.779, 123.68] #[0.28689553, 0.32513301, 0.28389176] #[0.37296272, 0.37296272, 0.37296272]
std                         : !!python/tuple [1.,1.,1.]             #[0.18696375, 0.19017339, 0.18720214]#[0.21090189, 0.21090189, 0.21090189]

# Data augmentation
hflips                      : True
random_dist                 : True

color_map                   : null
num_images                  : null